---
title: "1928-1969間，小兒麻痺在美國各州的發生率變化"
output: github_document
---

##資料前處理
把資料讀進來
```{r}
polio<-read.csv("POLIO_Incidence.csv",stringsAsFactors = F)
head(polio)
```

將寬表格轉為長表格
```{r}
#install.packages("ggplot2")
library(ggplot2)
#install.packages("reshape2")
library(reshape2)
polio.m<-melt(polio,id.vars = c('YEAR','WEEK'))
head(polio.m)
```

處理缺值
```{r}
polio.m[polio.m$value=="-",]$value<-NA #處理缺值,將"-"轉為NA
polio.m$value<-as.numeric(as.character(polio.m$value)) #將value欄位轉為數字
```

計算年度發生率
```{r}
polio.sumYear<- #各州各年度加總，計算該年度的總發生率
    aggregate(value~YEAR+variable,data=polio.m,FUN=sum,na.rm=F)
head(polio.sumYear)
```


##視覺畫呈現
使用Heatmap呈現，X軸為年度，Y軸為不同的州，以紅點來表示小兒麻痺發生率，深淺代表表發生率高低，在1955年紅點有減少減少
```{r}

ggplot(polio.sumYear, aes(YEAR, variable)) + #aes(x,y)
    geom_tile(aes(fill = value),colour = "white")+
  geom_vline(xintercept = 1955)+ #geom_tile: 區塊著色
    scale_fill_gradient(low = "white",high = "red") #數值低：白色

```

說明:
 可以從1928年到1969年的趨勢圖，看出美國各州的小兒麻痺在1955年以前，幾乎都是向上攀升的趨勢，直到1955年小兒麻痺疫苗的產生，可以看出疫苗是有幫助的。
